services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    networks:
      - shelfspace-net

  user-service:
    build: ./services/user-service
    ports:
      - "3002:3002"
    networks:
      - shelfspace-net

  user-library-service:
    build: ./services/user-library-service
    ports:
      - "3003:3003"
    networks:
      - shelfspace-net

  book-service:
    build: ./services/book-service
    ports:
      - "3004:3004"
    networks:
      - shelfspace-net

networks:
  shelfspace-net:
    driver: bridge
