services:
  nginx-gateway:
    image: nginx:stable-alpine
    ports:
      - "80:80"
    volumes:
      - ./api-gateway/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - shelfspace-net
    depends_on:
      - frontend
      - user-service
      - review-service
      - group-service
      - chat-service
      - admin-service
      - user-library-service
      - book-service
  frontend:
    build: ./frontend
    networks:
      - shelfspace-net

  user-service:
    build: ./services/user-service
    networks:
      - shelfspace-net

  review-service:
    build: ./services/review-service
    networks:
      - shelfspace-net

  group-service:
    build: ./services/group-service
    networks:
      - shelfspace-net

  chat-service:
    build: ./services/chat-service
    networks:
      - shelfspace-net

  admin-service:
    build: ./services/admin-service
    networks:
      - shelfspace-net

  user-library-service:
    build: ./services/user-library-service
    networks:
      - shelfspace-net

  book-service:
    build: ./services/book-service
    networks:
      - shelfspace-net

networks:
  shelfspace-net:
    driver: bridge
